# Generated by Django 5.1.4 on 2025-01-15 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_education_experience_profile_skill'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='type',
            field=models.CharField(choices=[('B', 'Bachelor'), ('M', 'Masters'), ('PHD', 'Philosophical Doctorate'), ('D', 'Diploma'), ('MD', 'Medical Doctorate'), ('O', 'Other')], default='B', max_length=3),
        ),
        migrations.AlterField(
            model_name='profile',
            name='title',
            field=models.CharField(choices=[('MR', 'Mr'), ('MISS', 'Miss'), ('MRS', 'Mrs'), ('MX', 'Mx'), ('MS', 'Ms'), ('O', 'Other')], default='MR', max_length=4),
        ),
    ]
